### PR TITLE
Italian translation

### PR DESCRIPTION
**Pull request by livinbits**
Italian translation, all "bonus tasks", and some doubts about the correct position of the added items in the "README.md" and "menu.js" files.

### CODE REVIEW

**Comment by bmoren** [comment]
This all looks great to me! Thank you!

**Comment by livinbits** [comment]
Thanks to you for sharing your project. 

I'm working on an extended version of the cheat sheet for my students at the Academy of Fine Arts:
https://github.com/livinbits/p5js-cheatsheet-forartists
Maybe you find some ideas or technical solutions that can be useful for you too.

**Comment by bmoren** [comment]
This looks fantastic as an expanded version! 

There are a bunch of things here that I was envisioning for the 'intermediate' sheet that would be printed on the back side of the beginner sheet.

The section on the HSB, system events, for loop, radians chart, and transformations especially!

I'd love to get that intermediate sheet started, is that something you'd be interested in working on, or if not, do you mind If I pull some of your fantastic work back over here to begin it?

More ideas / info here: https://github.com/bmoren/p5js-cheat-sheet/issues/2

**Comment by livinbits** [comment]
Unfortunately, I have to prepare some material (snippets, tutorials, and articles in Italian) for starting my course, and I'm not sure I can find the necessary time needed to take care of something else.

You can, however, take whatever you want from my cheat sheet, which I would not have been able to do fast enough without your valuable work.

**Pull request merged**
